'use client'
import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import DashboardSidebar from "@/components/dashboard-sidebar/DashboardSidebar";
import DashboardHeader from "@/components/dashboard-header/DashboardHeader";
import DashboardWrapper from "@/components/dashboard-wrapper/DashboardWrapper";

const roboto = Roboto({
  subsets: ["latin"],
  weight: "500"
});

// export const metadata: Metadata = {
//   title: "Dashboard Admin",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}> 
        <div className="flex min-h-screen">
          <DashboardSidebar  />
          <DashboardHeader  />
          <DashboardWrapper children = {children}></DashboardWrapper>
        </div>
      </body>
    </html>
  );
}
